[package]
name = "pingap-acl"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
keywords = ["pingap", "acl"]
description = "ACL and access lists for pingap"
# Not published: this crate exists only inside this workspace.
publish = false

[lib]
name = "pingap_acl"
path = "src/lib.rs"

[dependencies]

[lints]
workspace = true
