[package]
name = "pingap-adaptive"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "pingap_adaptive"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
ctor = { workspace = true }
humantime-serde = { workspace = true }
pingap-config = { workspace = true }
pingap-core = { workspace = true }
pingap-domainstate = { workspace = true }
pingap-plugin = { workspace = true }
pingora = { workspace = true }
serde = { workspace = true, features = ["derive"] }
snafu = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
